// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ9zWXSdBNDYsp7eWzHoilSUripaQODJc',
    appId: '1:591906641606:web:bc0a17ab4f1812358c69c7',
    messagingSenderId: '591906641606',
    projectId: 'chat-app-11213',
    authDomain: 'chat-app-11213.firebaseapp.com',
    storageBucket: 'chat-app-11213.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArz6iUIsK6keQYR93mV6pr4FO9WCWrqq0',
    appId: '1:591906641606:android:bf361a744feaf3bc8c69c7',
    messagingSenderId: '591906641606',
    projectId: 'chat-app-11213',
    storageBucket: 'chat-app-11213.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVPW0jy2vzeds2JwsRm4MyF5cmtXHTBE',
    appId: '1:591906641606:ios:6200c993ab791a3d8c69c7',
    messagingSenderId: '591906641606',
    projectId: 'chat-app-11213',
    storageBucket: 'chat-app-11213.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXVPW0jy2vzeds2JwsRm4MyF5cmtXHTBE',
    appId: '1:591906641606:ios:a45ddd8eada235cc8c69c7',
    messagingSenderId: '591906641606',
    projectId: 'chat-app-11213',
    storageBucket: 'chat-app-11213.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
